<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Chip_8_Emulator</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ROMS\BMP Viewer - Hello %28C8 example%29 [Hap, 2005].ch8">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ROMS\Chip8 Picture.ch8">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ROMS\Maze %28alt%29 [David Winter, 199x].ch8">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ROMS\pong.rom">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ROMS\pong2.rom">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ROMS\Tank.ch8">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ROMS\Tetris [Fran Dachille, 1991].ch8">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Shaders\shader.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Shaders\shader.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shaders\" />
  </ItemGroup>

</Project>
